# Generated by Django 5.0.4 on 2024-05-17 01:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255, verbose_name='Name')),
                ('email', models.CharField(default='', max_length=100, verbose_name='Email')),
                ('phone', models.CharField(default='', max_length=100, verbose_name='Phone Number')),
            ],
            options={
                'verbose_name': 'Users',
                'verbose_name_plural': 'Users',
            },
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(default='', max_length=255, verbose_name='Address')),
                ('secretcode', models.CharField(default='', max_length=255, verbose_name='SecretCode')),
                ('coinamount', models.CharField(default='', max_length=255, verbose_name='CoinAmount')),
                ('owner', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='wallet_username', to='homepage.users')),
            ],
            options={
                'verbose_name': 'Wallet',
                'verbose_name_plural': 'Wallet',
            },
        ),
        migrations.AddField(
            model_name='users',
            name='wallet_info',
            field=models.ManyToManyField(default='', related_name='owners', to='homepage.wallet'),
        ),
    ]
