# Generated by Django 5.0.4 on 2024-05-22 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoinPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coinprice', models.IntegerField(default=5.6)),
            ],
            options={
                'verbose_name': 'Coin Price',
                'verbose_name_plural': 'Coin Price',
            },
        ),
    ]
