# Generated by Django 5.0.4 on 2024-05-17 01:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users',
            new_name='CoinUsers',
        ),
    ]
