# Generated by Django 5.0.4 on 2024-05-22 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_coinprice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coinprice',
            name='coinprice',
            field=models.DecimalField(decimal_places=2, default=5.6, max_digits=10),
        ),
    ]
