# Generated by Django 5.0.4 on 2024-05-17 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_rename_users_coinusers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coinusers',
            name='name',
            field=models.CharField(default='', max_length=100, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='owner',
            field=models.CharField(max_length=100, verbose_name='Owner'),
        ),
    ]
