# Generated by Django 5.0.4 on 2024-05-22 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_alter_coinprice_coinprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='estate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
