# Generated by Django 5.0.4 on 2024-05-19 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0004_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='secretcode',
            field=models.CharField(default='', max_length=100),
        ),
    ]
