# Generated by Django 5.0.4 on 2024-06-24 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0004_user_estate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='coins',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
